// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: season.sql

package dal

import (
	"context"
)

const getSeason = `-- name: GetSeason :one
SELECT id, season_year, series FROM season
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSeason(ctx context.Context, id int32) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, id)
	var i Season
	err := row.Scan(&i.ID, &i.SeasonYear, &i.Series)
	return i, err
}
