// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: team.sql

package dal

import (
	"context"
)

const getTeam = `-- name: GetTeam :one
SELECT id, team_name, base FROM team
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeam(ctx context.Context, id int32) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.TeamName, &i.Base)
	return i, err
}
